#!/usr/bin/env python3
# Copyright (c) 2024-2025, Personal Robotics Laboratory
# License: BSD 3-Clause. See LICENSE.md file in root directory.

"""
This script performs a quantitative analysis of the manifold data generated by
manifold_explorer.py.

For each joint, it creates an overlapping histogram to visualize the distribution
of joint values for both feasible and infeasible configurations. This helps
identify which joints, and which specific ranges of motion for those joints,
are critical for the Articutool's leveling task.
"""

import argparse
import sys
import os
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import math


def analyze_joint_distributions(csv_file_path: str, output_dir: str):
    """
    Loads manifold data and generates overlapping histograms for each joint.
    """
    print(f"Loading data from {csv_file_path}...")
    try:
        df = pd.read_csv(csv_file_path)
    except FileNotFoundError:
        print(f"Error: File not found at '{csv_file_path}'", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error reading CSV file: {e}", file=sys.stderr)
        sys.exit(1)

    # --- Data Preparation ---
    # Get the names of the joint columns (assumes they start with 'j')
    joint_columns = [col for col in df.columns if col.startswith("j")]
    if not joint_columns:
        print(
            "Error: No joint columns (e.g., 'j1', 'j2') found in the CSV file.",
            file=sys.stderr,
        )
        sys.exit(1)

    # Separate the DataFrame into feasible and infeasible sets
    feasible_df = df[df["is_feasible"] == 1]
    infeasible_df = df[df["is_feasible"] == 0]

    print(
        f"Found {len(feasible_df)} feasible and {len(infeasible_df)} infeasible samples."
    )

    # --- Plotting ---
    # Create a subplot grid for all joints
    num_joints = len(joint_columns)
    rows = math.ceil(num_joints / 2)
    fig = make_subplots(
        rows=rows,
        cols=2,
        subplot_titles=[f"Joint {i + 1} Distribution" for i in range(num_joints)],
    )

    print("Generating joint distribution plots...")
    for i, joint in enumerate(joint_columns):
        row = (i // 2) + 1
        col = (i % 2) + 1

        # Add histogram for feasible configurations
        fig.add_trace(
            go.Histogram(
                x=feasible_df[joint],
                name="Feasible",
                marker_color="#2ca02c",  # Green
                opacity=0.7,
                legendgroup="feasible",
                showlegend=(i == 0),  # Show legend only for the first plot
            ),
            row=row,
            col=col,
        )

        # Add histogram for infeasible configurations
        fig.add_trace(
            go.Histogram(
                x=infeasible_df[joint],
                name="Infeasible",
                marker_color="#d62728",  # Red
                opacity=0.6,
                legendgroup="infeasible",
                showlegend=(i == 0),  # Show legend only for the first plot
            ),
            row=row,
            col=col,
        )

        fig.update_xaxes(title_text="Joint Value (radians)", row=row, col=col)
        fig.update_yaxes(title_text="Count", row=row, col=col)

    # Update the overall layout
    fig.update_layout(
        height=400 * rows,
        width=900,
        title_text="<b>Joint Value Distributions for Feasible vs. Infeasible Configurations</b>",
        barmode="overlay",  # Overlay histograms
        legend_title_text="Configuration Status",
    )

    # Save the plot to an HTML file
    output_filename = os.path.join(
        output_dir,
        f"joint_distributions_{os.path.basename(csv_file_path).replace('.csv', '.html')}",
    )
    fig.write_html(output_filename)
    print(f"\nSuccessfully saved analysis to:\n{output_filename}")


def main():
    parser = argparse.ArgumentParser(
        description="Analyze and visualize joint distributions from manifold data."
    )
    parser.add_argument(
        "csv_file", type=str, help="Path to the manifold data CSV file."
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="manifold_data",
        help="Directory to save the output HTML file.",
    )
    args = parser.parse_args()

    analyze_joint_distributions(args.csv_file, args.output_dir)


if __name__ == "__main__":
    main()
