# NOTE: You have to change this node name if you change the node name in the launchfile.
food_on_fork_detection:
  ros__parameters:
    # The FoodOnFork class to use
    model_class: "ada_feeding_perception.food_on_fork_detectors.FoodOnForkDistanceToNoFOFDetector"
    # The path to load the model from. Ignored if the empty string.
    # Should be relative to the `model_dir` parameter, specified in the launchfile.
    model_path: "distance_no_fof_detector_with_filters.npz"
    # Keywords to pass to the FoodOnFork class's constructor
    model_kws:
      - camera_matrix
    # Keyword arguments to pass to the FoodOnFork class's constructor
    model_kwargs:
      camera_matrix: [614.5933227539062, 0.0, 312.1358947753906, 0.0, 614.6914672851562, 223.70831298828125, 0.0, 0.0, 1.0]
    
    # The rate at which to detect and publish the confidence that there is food on the fork
    rate_hz: 10.0
    # The top-left  and bottom-right corners to crop the depth image to
    crop_top_left: [344, 272]
    crop_bottom_right: [408, 336]
    # The min and max depth to consider for the food on the fork
    depth_min_mm: 310
    depth_max_mm: 340

    # The size of the temporal window for the "temporal" post-processor.
    temporal_window_size: 5
    # The size of the square kernel for the "spatial" post-processor.
    spatial_num_pixels: 10

    # Whether to visualize the output of the detector
    viz: True
    # The upper and lower thresholds for the visualization to say there is(n't) food-on-fork
    viz_lower_thresh: 0.25
    viz_upper_thresh: 0.75