# NOTE: You have to change this node name if you change the node name in the launchfile.
republisher:
  ros__parameters:
    # The name of the topics to republish from
    from_topics:
      - /camera/color/image_raw/compressed
      - /camera/aligned_depth_to_color/image_raw

    # The types of topics to republish from
    topic_types:
      - sensor_msgs.msg.CompressedImage
      - sensor_msgs.msg.Image

    # The name of the topics to republish to
    to_topics:
      - /local/camera/color/image_raw/compressed
      - /local/camera/aligned_depth_to_color/image_raw