# NOTE: You have to change this node name if you change the node name in the launchfile.
table_detection:
  ros__parameters:
    # The rate at which to publish the pose of the detected table
    table_detection_rate_hz: 3.0

    # A boolean to determine whether to visualize plate detection 
    table_detection_viz: True

# NOTE: If using the combined perception node, be very careful to ensure no name clashes of parameters!
ada_feeding_perception:
  ros__parameters:
    # The rate at which to publish the pose of the detected table
    table_detection_rate_hz: 3.0

    # A boolean to determine whether to visualize plate detection 
    table_detection_viz: True
