# Copyright (c) 2024-2025, Personal Robotics Laboratory
# License: BSD 3-Clause. See LICENSE.md file in root directory.

# This file was modified by modify_ac_library.py
actions:
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.08
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 0.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.0
  grasp_torque: 4.0
  pre_force: 20.0
  pre_offset:
  - 0.0
  - 0.0
  - -0.025
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  pre_quat:
  - 0.0
  - 0.7071068
  - -0.7071068
  - 0.0
  pre_torque: 4.0
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.08
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 0.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.0
  grasp_torque: 4.0
  pre_force: 20.0
  pre_offset:
  - 0.0
  - 0.0
  - -0.04
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  pre_quat:
  - -0.174941
  - 0.6851245
  - 0.6851245
  - -0.174941
  pre_torque: 4.0
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.08
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 0.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.0
  grasp_torque: 4.0
  pre_force: 15.0
  pre_offset:
  - -0.01
  - 0.0
  - -0.025
  pre_pos:
  - -0.4949747468305832
  - 0.0
  - 0.6363961030678928
  pre_quat:
  - 0.1379497
  - 0.6935199
  - 0.6935199
  - 0.1379497
  pre_torque: 4.0
- ext_angular:
  - -0.4
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.08
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 0.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.0
  grasp_torque: 4.0
  pre_force: 20.0
  pre_offset:
  - 0.0
  - 0.0
  - -0.025
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  pre_quat:
  - 0.0
  - 0.7071068
  - -0.7071068
  - 0.0
  pre_torque: 4.0
- ext_angular:
  - -0.4
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.08
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 0.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.0
  grasp_torque: 4.0
  pre_force: 20.0
  pre_offset:
  - 0.0
  - 0.0
  - -0.04
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  pre_quat:
  - -0.174941
  - 0.6851245
  - 0.6851245
  - -0.174941
  pre_torque: 4.0
- ext_angular:
  - -0.4
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.08
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 0.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.0
  grasp_torque: 4.0
  pre_force: 15.0
  pre_offset:
  - -0.01
  - 0.0
  - -0.025
  pre_pos:
  - -0.4949747468305832
  - 0.0
  - 0.6363961030678928
  pre_quat:
  - 0.1379497
  - 0.6935199
  - 0.6935199
  - 0.1379497
  pre_torque: 4.0
- ext_angular:
  - -0.29940023070845145
  - 0.018936788724187546
  - -0.0009486224441275935
  ext_duration: 2.224894712388526
  ext_force: 50.0
  ext_linear:
  - -0.007221750355917799
  - 0.000984312510690585
  - 0.026957998153735216
  ext_torque: 4.0
  grasp_angular:
  - 0.043164810768924776
  - 0.29161461783103754
  - 0.05565710896678695
  grasp_duration: 0.9542838029084819
  grasp_force: 20.628485289480114
  grasp_linear:
  - 0.019235823439093823
  - -0.0102442601628834
  - -0.030280814265481275
  grasp_torque: 1.0
  pre_force: 1.9680640809243017
  pre_offset:
  - 0.002418366523682367
  - 0.009703169758235321
  - -0.02
  pre_pos:
  - 0.01215432550886536
  - 0.04876658792389915
  - 0.06980903419187809
  pre_quat:
  - 0.1193524
  - 0.9860264
  - -0.0486593
  - -0.1055426
  pre_torque: 4.0
# Skewer + Twirl for Noodles
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.03
  ext_torque: 4.0
  grasp_angular:
  - 0.0
  - 0.0
  - 0.0
  grasp_duration: 1.0
  grasp_force: 15.0
  grasp_linear:
  - 0.0
  - 0.0
  - 0.025
  grasp_torque: 4.0
  pre_force: 5.0
  pre_offset:
  - 0.0
  - 0.0
  - -0.08
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  pre_quat:
  - 0.0
  - 0.7071068
  - -0.7071068
  - 0.0
  pre_torque: 2.0
  retract_force: 20.0
  retract_torque: 4.0
  retract_duration: 1.0
  retract_linear: [0.035, 0.0, 0.2]
  retract_angular: [0.0, 0.0, 0.0]
  pre_move_into_primitive_name: "TWIRL_CW"
  pre_move_into_primitive_params: [4.0, 3.0]
  post_move_into_primitive_name: "TWIRL_CCW"
  post_move_into_primitive_params: [4.0, 3.0]
  post_acquisition_primitive_name: "NONE"
  post_acquisition_primitive_params: []
  jaco_ee_tilt_angle_min: 0.0
  jaco_ee_tilt_angle_max: 10.0
  align_to_robot_base: True
# Tilted scoop (45 deg polar angle from vertical)
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.015
  ext_torque: 4.0
  grasp_angular: [0.0, 0.0, 0.0]
  grasp_duration: 1.0
  grasp_force: 30.0
  grasp_linear: [0.025, 0.0, 0.005]
  grasp_torque: 4.0
  retract_force: 20.0
  retract_torque: 4.0
  retract_duration: 1.0
  retract_linear: [-0.075, 0.0, 0.0]
  retract_angular: [0.0, 0.0, 0.0]
  pre_force: 10.0
  pre_offset:
  - 0.035
  - 0.0
  - -0.05
  pre_pos:
  - 1.0
  - 0.0
  - 1.0
  pre_quat:
  - -0.271
  - -0.653
  - 0.653
  - 0.271
  pre_torque: 4.0
  pre_move_into_primitive_name: "NONE"
  pre_move_into_primitive_params: []
  post_move_into_primitive_name: "NONE"
  post_move_into_primitive_params: []
  post_acquisition_primitive_name: "VIBRATE_ROLL"
  post_acquisition_primitive_params: [2.0, 0.5, 1.0] # [frequency_hz, amplitude_rad, duration_sec]
  align_to_robot_base: True
# Tilted scoop (60 deg polar angle from vertical)
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.015
  ext_torque: 4.0
  grasp_angular: [0.0, 0.0, 0.0]
  grasp_duration: 1.0
  grasp_force: 30.0
  grasp_linear: [0.025, 0.0, 0.005]
  grasp_torque: 10.0
  retract_force: 20.0
  retract_torque: 4.0
  retract_duration: 1.0
  retract_linear: [-0.075, 0.0, 0.0]
  retract_angular: [0.0, 0.0, 0.0]
  pre_force: 10.0
  pre_offset:
  - 0.035
  - 0.0
  - -0.05
  pre_pos:
  - 1.0
  - 0.0
  - 1.0
  pre_quat:
  - -0.354065
  - -0.6119149
  - 0.6119149
  - 0.354065
  pre_torque: 4.0
  pre_move_into_primitive_name: "NONE"
  pre_move_into_primitive_params: []
  post_move_into_primitive_name: "NONE"
  post_move_into_primitive_params: []
  post_acquisition_primitive_name: "VIBRATE_ROLL"
  post_acquisition_primitive_params: [2.0, 0.5, 1.0] # [frequency_hz, amplitude_rad, duration_sec]
  align_to_robot_base: True
# Tilted scoop for liquids
- ext_angular:
  - 0.0
  - 0.0
  - 0.0
  ext_duration: 1.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.005
  ext_torque: 4.0
  grasp_angular: [0.0, 0.0, 0.0]
  grasp_duration: 0.0
  grasp_force: 30.0
  grasp_linear: [0.0, 0.0, 0.0]
  grasp_torque: 4.0
  retract_force: 20.0
  retract_torque: 4.0
  retract_duration: 0.0
  retract_linear: [0.0, 0.0, 0.0]
  retract_angular: [0.0, 0.0, 0.0]
  pre_force: 3.0
  pre_offset:
  - 0.025
  - 0.0
  - 0.0
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  move_above_dist_m: 0.15
  pre_quat:
  - -0.5
  - -0.5
  - 0.5
  - 0.5
  pre_torque: 1.0
  pre_move_into_primitive_name: "NONE"
  pre_move_into_primitive_params: []
  post_move_into_primitive_name: "NONE"
  post_move_into_primitive_params: []
  post_acquisition_primitive_name: "NONE"
  post_acquisition_primitive_params: []
  jaco_ee_tilt_angle_min: 30.0
  jaco_ee_tilt_angle_max: 40.0
  align_to_robot_base: True
# Scoop and level (6-DOF Baseline)
- ext_angular:
  - -0.1
  - 0.0
  - 0.0
  ext_duration: 10.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.01
  ext_torque: 4.0
  grasp_angular: [0.0, 0.0, 0.0]
  grasp_duration: 1.0
  grasp_force: 30.0
  grasp_linear: [0.025, 0.0, 0.005]
  grasp_torque: 10.0
  pre_force: 10.0
  pre_offset:
  - 0.035
  - 0.0
  - -0.05
  pre_pos:
  - 1.0
  - 0.0
  - 1.0
  pre_quat:
  - -0.271
  - -0.653
  - 0.653
  - 0.271
  pre_torque: 4.0
  align_to_robot_base: True
# Tilted scoop for liquids (6-DOF Baseline)
- ext_angular:
  - -0.1
  - 0.0
  - 0.0
  ext_duration: 10.0
  ext_force: 50.0
  ext_linear:
  - 0.0
  - 0.0
  - 0.01
  ext_torque: 4.0
  grasp_angular: [0.0, 0.0, 0.0]
  grasp_duration: 0.0
  grasp_force: 30.0
  grasp_linear: [0.0, 0.0, 0.0]
  grasp_torque: 4.0
  retract_force: 20.0
  retract_torque: 4.0
  retract_duration: 0.0
  retract_linear: [0.0, 0.0, 0.0]
  retract_angular: [0.0, 0.0, 0.0]
  pre_force: 3.0
  pre_offset:
  - 0.025
  - 0.0
  - 0.0
  pre_pos:
  - 0.0
  - 0.0
  - 1.0
  move_above_dist_m: 0.14
  pre_quat:
  - -0.2710956
  - -0.6528595
  - 0.6528595
  - 0.2710956
  # - -0.3541822
  # - -0.6118463
  # - 0.6118463
  # - 0.3541822
  pre_torque: 1.0
  pre_move_into_primitive_name: "NONE"
  pre_move_into_primitive_params: []
  post_move_into_primitive_name: "NONE"
  post_move_into_primitive_params: []
  post_acquisition_primitive_name: "NONE"
  post_acquisition_primitive_params: []
  align_to_robot_base: True
