# Copyright (c) 2024, Personal Robotics Laboratory
# License: BSD 3-Clause. See LICENSE.md file in root directory.

# Map of RGB colors to Action index
color_map:
    - # Default
      color: [0.0, 0.0, 0.0]
      index: 0
