# The interface for a service that takes in a list of input labels
# describing the food items on a plate and returns a sentence caption compiling
# these labels used as a query for GroundingDINO detection.

# A list of semantic labels corresponding to each of the masks of detected
# items in the image
string[] input_labels
---
# A sentence caption compiling the semantic labels used as a query for 
# GroundingDINO to perform bounding box detections.
string caption