# The interface for a generic service that takes in keys and json-encoded
# values for settings, sets them, and returns the keys of settings it
# succesfully set.

# Keys of the settings to set
std_msgs/String[] keys
# JSON-endoded values for the settings. json_values[0] is the value of keys[0].
# Therefore, `keys` and `json_values` must have the same length
std_msgs/String[] json_values
---
# Which keys were succesfully set
std_msgs/String[] success_keys