# The interface for a bite acquisition action that takes in a
# food mask as input, returns whether or not it succeeded, and gives progress
# in terms of how long it has been planning for and/or how much farther it has
# to move.

# The header for the image that the mask corresponds to
std_msgs/Header header
# The camera intrinsics
sensor_msgs/CameraInfo camera_info
# The mask for the food item the robot should acquire
ada_feeding_msgs/Mask detected_food
---
# Possible return statuses
uint8 STATUS_SUCCESS=0
uint8 STATUS_PLANNING_FAILED=1
uint8 STATUS_MOTION_FAILED=2
uint8 STATUS_CANCELED=3
uint8 STATUS_UNKNOWN=99

# Whether the planning and motion succeeded and if not, why
uint8 status

## Information to send to AcquisitionSelect service
# Action Taken
uint8 action_index

# Posthoc context
float64[] posthoc

# AcquisitionSelect call id
# Used in AcquisitionReport
string selection_id

---
# Whether the robot is currently planning or moving (required)
bool is_planning
# The amount of time the robot has spent in planning (required)
builtin_interfaces/Duration planning_time
# The amount of time the robot has spent in motion (required if `is_planning == false`)
builtin_interfaces/Duration motion_time
# How far the robot initially was from the goal (required if `is_planning == false`)
float64 motion_initial_distance
# How far the robot currently is from the goal (required if `is_planning == false`)
float64 motion_curr_distance
