# The interface for an action that gets an image from the camera and returns
# the masks of all segmented items within that image.

---
# The header for the image that the masks corresponds to
std_msgs/Header
# Masks of all the detected items in the image
ada_feeding_msgs/Mask[] detected_items
---
# How much time the action has spent segmenting the food item
builtin_interfaces/Duration elapsed_time