# The interface for a generic action that tells the robot to move with a
# particular velocity for a particular duration.

# The target velocity
geometry_msgs/TwistStamped vel
# How long to move at that velocity
builtin_interfaces/Duration duration
---
# Whether the robot successfully completed the motion
bool success
---
# How much time the action has spent moving
builtin_interfaces/Duration elapsed_time