# NOTE: You have to change this node name if you change the node name in the launchfile.
ada_feeding_action_servers:
  ros__parameters:
    # Parameters to specify the watchdog topic and timeout
    watchdog_topic: /ada_watchdog
    watchdog_timeout_sec: 0.5 # If we haven't received a message from the watchdog in this time, stop all robot motions

    # A list of the names of the action servers to create. Each one must have
    # it's own parameters (below) specifying action_type and tree_class.
    server_names:
      - MoveAbovePlate
      - AcquireFood
      - MoveToMouth
      - MoveToRestingPosition
      - MoveToStowLocation

    # Parameters for the MoveAbovePlate action
    MoveAbovePlate: # required
      action_type: ada_feeding_msgs.action.MoveTo # required
      tree_class: ada_feeding.trees.MoveToConfigurationTree # required
      tree_kws: # optional
        - action_type_class
        - joint_positions
      tree_kwargs: # optional
        action_type_class: ada_feeding_msgs.action.MoveTo # required
        joint_positions: # required
          - -2.11666 # j2n6s200_joint_1
          -  3.34967 # j2n6s200_joint_2
          -  2.04129 # j2n6s200_joint_3
          - -2.30031 # j2n6s200_joint_4
          - -2.34026 # j2n6s200_joint_5
          -  2.95450 # j2n6s200_joint_6
      tick_rate: 10 # Hz, optional, default: 30

    # Parameters for the AcquireFood action
    AcquireFood: # required
      action_type: ada_feeding_msgs.action.AcquireFood # required
      tree_class: ada_feeding.trees.MoveToDummyTree # required
      tree_kws: # optional
        - action_type_class
        - dummy_plan_time
        - dummy_motion_time
      tree_kwargs: # optional
        action_type_class: ada_feeding_msgs.action.AcquireFood # required
        dummy_plan_time: 1.0 # secs
        dummy_motion_time: 10.0 # secs
      tick_rate: 10 # Hz, optional, default: 30

   # Parameters for the MoveToRestingPosition action
    MoveToRestingPosition: # required
      action_type: ada_feeding_msgs.action.MoveTo # required
      tree_class: ada_feeding.trees.MoveToConfigurationTree # required
      tree_kws: # optional
        - action_type_class
        - joint_positions
      tree_kwargs: # optional
        action_type_class: ada_feeding_msgs.action.MoveTo # required
        joint_positions: # required
          - -1.94672 # j2n6s200_joint_1
          -  2.51268 # j2n6s200_joint_2
          -  0.35653 # j2n6s200_joint_3
          - -4.76501 # j2n6s200_joint_4
          -  5.99991 # j2n6s200_joint_5
          -  4.99555 # j2n6s200_joint_6
      tick_rate: 10 # Hz, optional, default: 30

    # Parameters for the MoveToMouth action
    # TODO: This is a dummy MoveToMouth implementation used to test MoveToPose.
    # It will be replaced with the actual MoveToMouth action once that is
    # implemented.
    MoveToMouth: # required
      action_type: ada_feeding_msgs.action.MoveTo # required
      tree_class: ada_feeding.trees.MoveToPoseTree # required
      tree_kws: # optional
        - action_type_class
        - position
        - quat_xyzw
      tree_kwargs: # optional
        action_type_class: ada_feeding_msgs.action.MoveTo # required
        position:
          -  0.27971 # x
          -  0.07175 # y
          -  0.77314 # z
        quat_xyzw:
          -  0.00175 # x
          -  0.70159 # y
          -  0.71255 # z
          - -0.00636 # w
      tick_rate: 10 # Hz, optional, default: 30

    # Parameters for the MoveToStowLocation action
    # TODO: We may be able to get a stow location that actually
    # tucks to the side of the user's wheelchair.
    MoveToStowLocation: # required
      action_type: ada_feeding_msgs.action.MoveTo # required
      tree_class: ada_feeding.trees.MoveToConfigurationTree # required
      tree_kws: # optional
        - action_type_class
        - joint_positions
      tree_kwargs: # optional
        action_type_class: ada_feeding_msgs.action.MoveTo # required
        joint_positions: # required
          - -1.52101 # j2n6s200_joint_1
          -  2.60098 # j2n6s200_joint_2
          -  0.32811 # j2n6s200_joint_3
          - -4.00012 # j2n6s200_joint_4
          -  0.22831 # j2n6s200_joint_5
          -  3.87886 # j2n6s200_joint_6
      tick_rate: 10 # Hz, optional, default: 30