# NOTE: You have to change this node name if you change the node name in the launchfile.
ada_planning_scene:
  ros__parameters:
    object_ids: # list of objects to add to the planning scene
      - wheelchair
      - wheelchair_collision
      - table
      - head
      - workspace_wall_front
      - workspace_wall_left
      - workspace_wall_right
      - workspace_wall_top
      # - food
    # For each object, specify:
    #   - Shape: EITHER `filepath` (for a mesh) OR `primitive_type` and
    #     `primitive_dims`(for a primitive -- see shape_msgs/SolidPrimitive.msg)
    #   - Pose: `position` and `quat_xyzw` (see geometry_msgs/Pose.msg)
    #   - Frame ID: `frame_id` (the frame_id of the object that the pose is
    #     relative to)
    #   - [Optional] to attach the collision object specify `attached` to be True.
    #     In that case, `frame_id` must be a link on the robot to attach the object
    #     to, and `touch_links` must be a list of additional links that should be
    #     ignored for collision checking.
    wheelchair: # the wheelchair mesh
      filename: wheelchair.stl
      position: [0.02, -0.02, -0.05]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      frame_id: root # the frame_id that the pose is relative to
    # an expanded mesh around the wheelchair to account for a user sitting in it
    # NOTE: If you change this you must also change the hardcoded initial pose in
    # btie transfer.
    wheelchair_collision: 
      filename: wheelchair_collision.stl
      position: [0.02, -0.02, -0.05] # should match the wheelchair position
      quat_xyzw: [0.0, 0.0, 0.0, 1.0] # should match the wheelchair orientation
      frame_id: root # the frame_id that the pose is relative to
    table: # the table mesh
      filename: table.stl
      position: [0.08, -0.5, -0.48]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      frame_id: root # the frame_id that the pose is relative to
    # NOTE: If you change this you must also change the hardcoded initial pose in
    # btie transfer.
    head: # the head mesh
      filename: tom.stl
      # This is an initial guess of head position; it will be updated as the
      # robot perceives the face.
      position: [0.29, 0.35, 0.85]
      quat_xyzw: [-0.0616284, -0.0616284, -0.704416, 0.704416]
      frame_id: root # the frame_id that the pose is relative to
    workspace_wall_front:
      primitive_type: 1 # Box=1. See shape_msgs/SolidPrimitive.msg
      primitive_dims: [1.59, 0.01, 0.85] # Box has 3 dims: [x, y, z]
      position: [-0.05, -0.58, 0.675]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      frame_id: root # the frame_id that the pose is relative to
    workspace_wall_left:
      primitive_type: 1 # Box=1. See shape_msgs/SolidPrimitive.msg
      primitive_dims: [0.01, 1.5, 1.65] # Box has 3 dims: [x, y, z]
      position: [0.75, 0.17, 0.275]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      frame_id: root # the frame_id that the pose is relative to
    workspace_wall_right:
      primitive_type: 1 # Box=1. See shape_msgs/SolidPrimitive.msg
      primitive_dims: [0.01, 1.5, 1.65] # Box has 3 dims: [x, y, z]
      position: [-0.3, 0.17, 0.275]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      frame_id: root # the frame_id that the pose is relative to
    workspace_wall_top:
      primitive_type: 1 # Box=1. See shape_msgs/SolidPrimitive.msg
      primitive_dims: [1.59, 1.5, 0.01] # Box has 3 dims: [x, y, z]
      position: [-0.05, 0.17, 1.1]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      frame_id: root # the frame_id that the pose is relative to
    food:
      primitive_type: 2 # Sphere=2. See shape_msgs/SolidPrimitive.msg
      primitive_dims: [0.05] # Sphere has 1 dim: [radius]
      position: [0.0, 0.0, 0.0]
      quat_xyzw: [0.0, 0.0, 0.0, 1.0]
      attached: True
      frame_id: forkTip # the frame_id that the pose is relative to
      touch_links: [forkTine] # the links, in addition to frame_id, that should be ignored for collision checking
