# A list of all the action servers to create. Each entry in the list 
# should have a server_name, action_type, and tree_class.
action_servers:
  - server_name: "MoveAbovePlate" # required
    action_type: "ada_feeding_msgs.action.MoveTo" # required
    tree_class: "ada_feeding.trees.MoveAbovePlate" # required
    tree_kwargs: # optional
      dummy_plan_time: 1.0 # secs
      dummy_motion_time: 10.0 # secs
    tick_rate: 10 # Hz, optional, default: 30