# NOTE: You have to change this node name if you change the node name in the launchfile.
ada_watchdog:
  ros__parameters:
    ############################################################################
    # Parameters for the watchdog as a whole
    ############################################################################
    # The rate at which to publish the watchdog message
    publish_rate_hz: 60.0
    # Whether or not to use the estop button. This should only be set false in
    # sim, because we currently have no way of simulating the estop button.
    use_estop: true

    ############################################################################
    # Parameters for the FTSensorCondition of the watchdog
    ############################################################################

    # If the force_torque sensor has not published a message in this amount of time,
    # or any of its dimensions are zero-variance in this amount of time, the watchdog 
    # will trigger a fault.
    ft_timeout_sec: 0.5

    ############################################################################
    # Parameters for the EStopCondition of the watchdog
    ############################################################################

    # The rate at which to sample fromt eh microphone (the e-stop button)
    rate: 48000
    # The number of samples to take at a time. If you are getting overflow
    # errors, try increasing this number.
    chunk: 4800
    # The device ID of the microphone (e-stop button). This should usually
    # be 0, the system default
    device: 0
    # How long to wait before checking the microphone readings. This is because
    # there is initial noise when we first listen to the microphone.
    initial_wait_secs: 2.0
    # The ACPI event for when the microphone is (un)plugged. To find this, run
    # `acpi_listen` in a terminal and plug/unplug the microphone. The output
    # should look something like this:
    #   jack/microphone MICROPHONE plug
    #   jack/microphone MICROPHONE unplug
    # Include the first two words in this parameter, exclude the third.
    acpi_event_name: "jack/microphone MICROPHONE"
