# NOTE: You have to change this node name if you change the node name in the launchfile.
ada_watchdog:
  ros__parameters:
    # If the force_torque sensor has not published a message in this amount of time,
    # or any of its dimensions are zero-variance in this amount of time, the watchdog 
    # will trigger a fault.
    ft_timeout_sec: 0.5
    # The rate at which to publish the watchdog message
    publish_rate_hz: 60.0
