# NOTE: You have to change this node name if you change the node name in the launchfile.
ada_feeding_action_servers:
  ros__parameters:
    # A list of the names of the action servers to create. Each one must have
    # it's own parameters (below) specifying action_type and tree_class.
    server_names:
      - MoveAbovePlate

    # Parameters for the MoveAbovePlate action
    MoveAbovePlate: # required
      action_type: ada_feeding_msgs.action.MoveTo # required
      tree_class: ada_feeding.trees.MoveAbovePlateTree # required
      tree_kws: # optional
        - action_type_class
      tree_kwargs: # optional
        action_type_class: ada_feeding_msgs.action.MoveTo # required
      tick_rate: 10 # Hz, optional, default: 30